apiVersion: apps/v1
kind: Deployment
metadata:
  name: {pod_name:s}
spec:
  selector:
    matchLabels:
      app: {pod_name:s}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {pod_name:s}
    spec:
      containers:
        - image: plato/{container_name:s}:v1
          name: {pod_name:s}
          resources:
            requests:
              memory: "{memory_requirement:s}"
              cpu: "{cpu_requirement:f}"
              nvidia.com/gpu: "{gpu_requirement:d}"
            limits:
              memory: "{memory_requirement:s}"
              cpu: "{cpu_requirement:f}"
              nvidia.com/gpu: "{gpu_requirement:d}"
          command: [ './launch_service_mode.py' ]
          args: [  ]
          volumeMounts:
            - name: output-persistent-storage
              mountPath: /plato-wp36-v2/data/datadir_output
            - name: input-persistent-storage
              mountPath: /plato-wp36-v2/data/datadir_input
      volumes:
        - name: output-persistent-storage
          persistentVolumeClaim:
            claimName: output-pv-claim
        - name: input-persistent-storage
          persistentVolumeClaim:
            claimName: input-pv-claim
