apiVersion: apps/v1
kind: Deployment
metadata:
  name: {pod_name:s}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {pod_name:s}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {pod_name:s}
    spec:
      containers:
        - image: plato/{container_name:s}:v1
          name: {pod_name:s}
          resources:
            requests:
              memory: "{memory_requirement:s}"
              cpu: "{cpu_requirement:f}"
              nvidia.com/gpu: "{gpu_requirement:d}"
            limits:
              memory: "{memory_requirement:s}"
              cpu: "{cpu_requirement:f}"
              nvidia.com/gpu: "{gpu_requirement:d}"
          command: [ './launch_service_mode.py' ]
          args: [ '--db_engine', '{db_engine:s}', '--db_user', '{db_user:s}', '--db_passwd', '{db_passwd:s}',
                  '--db_host', '{db_host:s}', '--db_port', '{db_port:d}', '--db_name', '{db_name:s}',
                  '--queue_implementation', '{queue_implementation:s}', '--mq_user', '{mq_user:s}',
                  '--mq_passwd', '{mq_passwd:s}', '--mq_host', '{mq_host:s}', '--mq_port', '{mq_port:d}' ]
          volumeMounts:
            - name: output-persistent-storage
              mountPath: /plato-wp36-v2/data/datadir_output
            - name: input-persistent-storage
              mountPath: /plato-wp36-v2/data/datadir_input
      volumes:
        - name: output-persistent-storage
          persistentVolumeClaim:
            claimName: output-pv-claim
        - name: input-persistent-storage
          persistentVolumeClaim:
            claimName: input-pv-claim
