apiVersion: v1
kind: PersistentVolume
metadata:
  name: input-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/datadir_input/"
