apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: taskQueue
    component: rabbitmq
  ports:
    - port: 5672
      nodePort: 30672
      targetPort: 5672
