apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: eas-web-interface
  name: eas-web-interface
spec:
  selector:
    matchLabels:
      app: eas-web-interface
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eas-web-interface
        component: eas-web-interface
    spec:
      containers:
        - image: plato/eas_web_interface:v1
          name: eas-web-interface
          command: [ './web_interface.py' ]
          args: [ ]
          volumeMounts:
            - name: output-persistent-storage
              mountPath: /plato-wp36-v2/data/datadir_output
            - name: input-persistent-storage
              mountPath: /plato-wp36-v2/data/datadir_input
      volumes:
        - name: output-persistent-storage
          persistentVolumeClaim:
            claimName: output-pv-claim
        - name: input-persistent-storage
          persistentVolumeClaim:
            claimName: input-pv-claim
