apiVersion: v1
kind: Service
metadata:
  labels:
    component: eas-web-interface
  name: eas-web-interface-service
spec:
  type: NodePort
  selector:
    app: eas-web-interface
  ports:
    - port: 5000
      nodePort: 30080
      targetPort: 5000
